### PR TITLE
Updated all APIs

### PR DESCRIPTION
**Pull request by doodlezucc**
I mainly followed the readme steps to contribute, but didn't know how to include all the updates (of which there are a lot) in the changelog.
Originally, I just wanted to update the YouTube API because some parameters were missing. When I ran the generator in a cloud shell, every library seemed to be out of date and had to be updated. Is this default behavior?

Anyway, all tests passed in the stable and beta directories.

### CODE REVIEW

**Comment by doodlezucc** [comment]
@googlebot I signed it!

**Comment by mkustermann** [comment]
I'll defer the review to @jonasfj who has been updating this package lately.

**Comment by doodlezucc** [comment]
Okay so I don't know why this happened but, looking at some of the diffs, basically nothing changed. It's pretty much all just reordering of parameters, not even alphabetically or in any particular manner.
I'm not sure if the order actually changed in almost every single one of Google's APIs or if this was just a mistake on my part. 

There are some minor additions though, for example [here](https://github.com/dart-lang/googleapis/pull/121/files#diff-62724ffadadb1a0aa7c8076be7803007b96187b039917cca158a427ec123b952R7422-R7445) (might take some time to load).

Anyway, you can safely reject this pull request as it doesn't actually add much to the plugin but still declares "breaking changes" in its changelog. Sorry for opening a pull request without recognizing what's different.

Also, nevermind this:
> Originally, I just wanted to update the YouTube API because some parameters were missing.

As it turned out, I was trying to use parameters on the wrong function (didn't have my coffee).

**Comment by jonasfj** [comment]
> I'm not sure if the order actually changed in almost every single one of Google's APIs or if this was just a mistake on my part.

Yeah, we should probably normalize the JSON before we save and generate APIs... :D

**Pull request closed without merging**
